### ISSUE TITLE
Do you have the URDF model of EA66?

### ISSUE THREAD

**Issue by hahaha-di** [Elite-Robots/Elite_Robots_CS_ROS2_Driver#4]

**Comment by SupermanOfHeiLinPu** [comment]
EA66 is not CS series robots. You can submit the issue in the repository below: https://github.com/Elite-Robots/ROS

**Comment by hahaha-di** [comment]
好的  非常感谢您的回复

> EA66 is not CS series robots. You can submit the issue in the repository below: https://github.com/Elite-Robots/ROS
